# Generated by Django 3.1.3 on 2020-11-30 18:58

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_FORM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainform',
            name='Numer_tel',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
