# Generated by Django 3.1.3 on 2020-12-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_FORM', '0002_auto_20201130_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainform',
            name='Zgoda_1',
            field=models.BooleanField(default=False),
        ),
    ]
