# Generated by Django 3.1.3 on 2020-12-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MAIN_FORM', '0005_auto_20201205_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainform',
            name='Data_polisy',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mainform',
            name='Data_przegladu',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='ZgodaInfHandlowa',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='ZgodaMarketing',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='ZgodaMarketingBezp',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mainform',
            name='ZgodaPrzeglad',
            field=models.BooleanField(default=True),
        ),
    ]
